---

name: integration-tests
run-name: Run integration tests
on:
  pull_request:
    branches:
      - master
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Run tests
        run: bash run_tests.sh
